DidEats/DidEats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio,name='inicio'),
    path('comidas/',include('comidas.urls')),
    path('tiendas/',include('tiendas.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns +={
    path('accounts/',include('django.contrib.auth.urls')),
}

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DidEats/comidas/urls.py
from django.urls import path
from .views import *

app_name='comidas'

urlpatterns = [
	path('',IndexView.as_view(), name='allfoods'),
	path('<str:pk>/', DetailView.as_view(), name='details'),
	path('mantenedor/create/', ComidaCreate, name='crear'),
	path('mantenedor/buscar/', ComidaSearch, name='buscar'),
	path(r'mantenedor/editar/<pk>/', ComidaUpdate, name='editar'),
	path(r'mantenedor/Eliminar/<pk>/', ComidaDelete, name='eliminar'),
]

DidEats/tiendas/urls.py
from django.urls import path
from .views import *

app_name = 'tiendas'

urlpatterns = [
	path('',IndexView.as_view(), name='allstores'),
	path('<str:pk>/', DetailView.as_view(), name='details'),
	path('mantenedor/create/', TiendaCreate, name='crear'),
	path('mantenedor/buscar/', TiendaSearch, name='buscar'),
	path(r'mantenedor/editar/<pk>/', TiendaUpdate, name='editar'),
	path(r'mantenedor/Eliminar/<pk>/', TiendaDelete, name='eliminar'),
]

DidEats/comidas/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Comida(models.Model):
	"""docstring for Comida"""
	comida_id = models.CharField(max_length=10,help_text="Ingrese ID de la comida",primary_key=True)
	comida_nombre = models.CharField(max_length=200, help_text="Ingrese Nombre de la comida")
	comida_valor=models.IntegerField(help_text="Ingrese el precio de la comida (Ej: $ 999 999).")
	comida_descripcion=models.TextField(max_length=3000, help_text="Ingrese la descripcion de la comida")
	comida_imagen=models.ImageField(upload_to="gallery", null=True)

	def __str__(self):
		return self.comida_nombre

	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('comidas:details', args=[str(self.comida_id)])

DidEats/comidas/forms.py
from django import forms

from .models import Comida

class ComidaCreateForm(forms.ModelForm):
	"""docstring for ComidaCreateForm"""
	comida_id = forms.CharField(label = "ID", required=True,
					widget = forms.TextInput(
						attrs={
							"placeholder":"Ingrese la id de la comida",
							"minlength":3
						}
					)
				)
	comida_nombre = forms.CharField(label="Nombre Comida", required=True,
                widget=forms.TextInput(
                        attrs={
                            "placeholder":"Ingrese el nombre de la comida",
                            "minlength":5
                        }
                )   
            )
	comida_valor = forms.IntegerField(label="Precio", required =True,
                    widget=forms.NumberInput(
                        attrs={
                            "placeholder":"Precio Comida"
                        }
                    )
                )
	comida_descripcion = forms.CharField(label="Descripcion", required=True,
                widget=forms.Textarea(
                        attrs={
                            "placeholder":"Ingrese descripcion de la comida",
                            "minlength":5,
                            "maxlength":3000
                        }
                )   
            )
	comida_imagen = forms.ImageField(label="Imagen principal")

	class Meta:
		"""docstring for Meta"""
		model = Comida
		fields = [
			'comida_id',
			'comida_nombre',
			'comida_valor',
			'comida_descripcion',
			'comida_imagen'
		]
			

DidEats/comidas/views.py
from django.shortcuts import render
from .models import Comida
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from .forms import ComidaCreateForm
# Create your views here.

class IndexView(generic.ListView):
    model = Comida
    template_name = 'comidas/comidas_lista.html'
    def get_queryset(self):
        return Comida.objects.all() 

class DetailView(generic.DetailView):
	model = Comida

def ComidaCreate(request):
	form = ComidaCreateForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit = True)
		instance.save()
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		'title' : "Crear",
		'form':form
	}
	return render(request, 'comidas/comida_crear.html',context)

def ComidaSearch(request, id=None):

	queryset = Comida.objects.all()
	query = request.GET.get("q")
	if query:
			queryset = queryset.filter(comida_id__icontains=query)
	context = {
		"object_list" : queryset,
		"title" : "Buscar"
	}
	return render(request, "comidas/comidas_buscar.html",context)

def ComidaUpdate(request, pk = None):
    instance = get_object_or_404(Comida, comida_id = pk)
    form = ComidaCreateForm(request.POST or None, request.FILES or None,instance=instance)
    if form.is_valid():
        instance = form.save(commit=True)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Editar",
        "instance":instance,
        "form" : form
    }
    return render(request, "comidas/comida_crear.html",context)


def ComidaDelete(request, pk= None):
    instance = get_object_or_404(Comida, comida_id = pk)
    instance.delete()
    return redirect("comidas:buscar")

DidEats/templates/comidas/comida_crear.html
{% extends "main_template.html" %}

{% load humanize %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static '/style.css' %}">
<link rel="stylesheet" href="{% static '/menu/menustyle.css' %}">
<header>
        <div class="contenedor">
            <div class="marca">
                <h1><span class="resaltado">DidEatsYa!</span> Pide, espera y disfruta!</h1>
            </div>
            <nav>
                <ul>
                    <li id="1"><a href="{% url 'inicio' %}">Inicio</a></li>
                    <li id="2"><a href="{% url 'comidas:allfoods' %}">Comidas</a></li>
                    <li id="3"><a href="{% url 'tiendas:allstores' %}">Tiendas</a></li>
                    {% if user.is_authenticated %}
                            <li style="width:12%" class="navli"><a href="#">{{ user.get_username }}</a>
                                <ul class="child">
                                    <li><a href= "{{ user.cuenta.get_absolute_url }}">Profile</a></li>
                                    {% if user.is_superuser %}
                                        <li class="actual"><a href="{% url 'comidas:buscar' %}">Mantenedor Comida</a></li>
                                        <li><a href="{% url 'tiendas:buscar' %}">Mantenedor Tiendas</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{request.path}}">Login</a>
                        {% endif %}
                </ul>
            </nav>
        </div>
</header>

<div class="container">
    {% include 'comidas/lateral_bar.html' %}
    <div class="row">
        <div class="col-lg-20">
            <div class="card-body">
                <h3 class="card-title">Mantenedor de Comida</h3>
                <h4>Ingresar los datos</h4>
                <p id="error"> Porfavor Corrija las casillas marcadas en rojo</p>
                <p id="succes"> La Información se Envió correctamente, por favor verifique si E-mail.</p>
                <div class="tab-pane fade show active" id="usr" role="tabpanel" aria-labelledby="home-tab">
                    <form enctype="multipart/form-data" method="POST">{% csrf_token %} 
                        
                        {{ form.as_p }}
                        
                        <input type="submit" value="{{ title }}"> 
                    </form>
                
                </div>
            </div>
        </div>
    </div> 
</div>
{% endblock %}|

DidEats/templates/comidas/comida_detail.html
{% extends "main_template.html" %}

{% load humanize %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static '/style.css' %}">
<link rel="stylesheet" href="{% static '/menu/menustyle.css' %}">
<header>
        <div class="contenedor">
            <div class="marca">
                <h1><span class="resaltado">DidEatsYa!</span> Pide, espera y disfruta!</h1>
            </div>
            <nav>
                <ul>
                    <li id="1"><a href="{% url 'inicio' %}">Inicio</a></li>
                    <li id="2" class="actual"><a href="{% url 'comidas:allfoods' %}">Comidas</a></li>
                    <li id="3"><a href="{% url 'tiendas:allstores' %}">Tiendas</a></li>
                    {% if user.is_authenticated %}
                            <li style="width:12%" class="navli"><a href="#">{{ user.get_username }}</a>
                                <ul class="child">
                                    <li><a href= "{{ user.cuenta.get_absolute_url }}">Profile</a></li>
                                    {% if user.is_superuser %}
                                        <li><a href="{% url 'comidas:buscar' %}">Mantenedor Comida</a></li>
                                        <li><a href="{% url 'tiendas:buscar' %}">Mantenedor Tiendas</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{request.path}}">Login</a>
                        {% endif %}
                </ul>
            </nav>
        </div>
</header>
<div class="container">
    <!--MAIN-->
    <div class="col-lg-12">

        <!--CARRUSEL-->
        <div class="card mt-4">
            <div id="demo" class="carousel slide" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                </ul>
        
                <!-- The slideshow -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ object.comida_imagen.url }}" alt="Imagen Principal" style="width:1000px;height: 570px;">
                    </div>
                </div>
            </div>
        </div>

        <!--TEXTO DE PROD-->
        <div class="card-body">
            <h3 class="card-title">{{ object.comida_nombre }}</h3>
            <h4>$ {{ object.comida_valor|intcomma }}</h4>
            <button type="button" class="btn btn-secondary" id="agregar" onclick="cambio()">Agregar al carrito</button>
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars
            <div class="row-sm1">
                <h4><br></h4>
            </div>
            <ul class="nav nav-pills" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#descr" role="tab" aria-controls="descr" aria-selected="true">Descripción</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#rev" role="tab" aria-controls="rev" aria-selected="false">Reseñas</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="descr" role="tabpanel" aria-labelledby="home-tab">
                    <p class="card-text">
                        <br>
                        {{ object.comida_descripcion }}
                    </p>
                </div>
                <div class="tab-pane fade" id="rev" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="card card-outline-secondary my-4">
                        <div class="card-header">
                            Reseñas del producto
                        </div>
                        <div class="card-body">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <a href="#" class="btn btn-success">Deja tu reseña</a>
                        </div>
                    </div>
                </div>
            </div>
         </div>
    </div>
</div>
{% endblock %}

DidEats/templates/comidas/comidas_buscar.html
{% extends "main_template.html" %}

{% load humanize %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static '/style.css' %}">
<link rel="stylesheet" href="{% static '/menu/menustyle.css' %}">
<header>
        <div class="contenedor">
            <div class="marca">
                <h1><span class="resaltado">DidEatsYa!</span> Pide, espera y disfruta!</h1>
            </div>
            <nav>
                <ul>
                    <li id="1"><a href="{% url 'inicio' %}">Inicio</a></li>
                    <li id="2"><a href="{% url 'comidas:allfoods' %}">Comidas</a></li>
                    <li id="3"><a href="{% url 'tiendas:allstores' %}">Tiendas</a></li>
                    {% if user.is_authenticated %}
                            <li style="width:12%" class="navli"><a href="#">{{ user.get_username }}</a>
                                <ul class="child">
                                    <li><a href= "{{ user.cuenta.get_absolute_url }}">Profile</a></li>
                                    {% if user.is_superuser %}
                                        <li class="actual"><a href="{% url 'comidas:buscar' %}">Mantenedor Comida</a></li>
                                        <li><a href="{% url 'tiendas:buscar' %}">Mantenedor Tiendas</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{request.path}}">Login</a>
                        {% endif %}
                </ul>
            </nav>
        </div>
</header>
<div class="container">
  {% include 'comidas/lateral_bar.html' %}
  <div class="row">
    <div class="col">
      <div class="card-body">
          <h3 class="card-title">Mantenedor de Comida</h3>
          <form method="GET" action="">
              <input type="text" name="q" placeholder="Introduzca la Id de la comida" >
              <input type="submit" name="Serch" value = "{{ title }}">

          </form>

      </div>
      <table class="table">
        <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Valor</th>
          <th>Opciones</th>
        </tr>
        </thead>
        
        <tbody>
          
          {% for object in object_list %}
          <tr>
            <th scope="row">{{ object.comida_id }}</th>
            <td>{{ object.comida_nombre }}</td>
            <td>{{ object.comida_valor }}</td>
            <td>
              <a href="{{ object.get_absolute_url }}" class="btn btn-secondary" >Mostrar</a>
              <a href="{% url 'comidas:editar' pk=object.comida_id %}" class="btn btn-secondary" >Editar</a>
              <a href="{% url 'comidas:eliminar' pk=object.comida_id %}" class="btn btn-secondary" >Eliminar</a>
            </td>
          </tr>

          {% endfor %}
          
        </tbody>
      </table>
    </div> 
  </div>
</div>
{% endblock %}

DidEats/templates/comidas/comidas_lista.html
{% extends "main_template.html" %}

{% load humanize %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static '/style.css' %}">
<link rel="stylesheet" href="{% static '/menu/menustyle.css' %}">
<header>
		<div class="contenedor">
			<div class="marca">
				<h1><span class="resaltado">DidEatsYa!</span> Pide, espera y disfruta!</h1>
			</div>
			<nav>
				<ul>
					<li id="1"><a href="{% url 'inicio' %}">Inicio</a></li>
					<li id="2" class="actual"><a href="{% url 'comidas:allfoods' %}">Comidas</a></li>
					<li id="3"><a href="{% url 'tiendas:allstores' %}">Tiendas</a></li>
					{% if user.is_authenticated %}
                            <li style="width:12%" class="navli"><a href="#">{{ user.get_username }}</a>
                                <ul class="child">
                                    <li><a href= "{{ user.cuenta.get_absolute_url }}">Profile</a></li>
                                    {% if user.is_superuser %}
                                        <li><a href="{% url 'comidas:buscar' %}">Mantenedor Comida</a></li>
                                        <li><a href="{% url 'tiendas:buscar' %}">Mantenedor Tiendas</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{request.path}}">Login</a>
                        {% endif %}
				</ul>
			</nav>
		</div>
</header>
<div class="container" style="margin-top: 20px">
    <header class="header">
        <h2>Comida</h2>
    </header>
    {% for Comida in object_list %}
    <div class="row">
        <div class="col-md-12 col-md-12 col-md-12">
            <div class="card h-100">
                {% load static %}<a href="{{ Comida.get_absolute_url }}"><img src="{{ Comida.comida_imagen.url }}" class ="imagenresp" style="width: 100%;"></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <center><a href="{{ Comida.get_absolute_url }}">{{ Comida.comida_nombre }}</a></center>
                    </h4>
                    <center><h6>$ {{ Comida.comida_valor|intcomma }}</h6></center>
                        <p class="card-text"></p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

DidEats/templates/comidas/lateral_bar.html
<div class="col-lg-20 d-none d-lg-table-cell">
        <div class="list-group">
            <a class="list-group-item nav-link" href="{% url 'comidas:crear' %}">Crear Comida</a>
            <a class="list-group-item nav-link" href="{% url 'comidas:buscar' %}">Listar Comida</a>
            <a class="list-group-item nav-link" href="{% url 'tiendas:crear' %}">Crear Tienda</a>
            <a class="list-group-item nav-link" href="{% url 'tiendas:buscar' %}">Listar Tienda</a>
        </div>
</div>